package view;

import controller.AutoTestHandler;

/**
 *
 * @author LongNguyen & NghiaPham
 */

public class AutoTestView extends javax.swing.JFrame {

    /**
     * Creates new form AutoTestView
     */
    
    public AutoTestView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectLabel = new javax.swing.JLabel();
        jInputTextField = new javax.swing.JTextField();
        jLabelInput = new javax.swing.JLabel();
        jLabelOutput = new javax.swing.JLabel();
        jOutputTextField = new javax.swing.JTextField();
        jBrowseInputButton = new javax.swing.JButton();
        jBrowseOutputButton = new javax.swing.JButton();
        jExitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jNonReviewCheckBox = new javax.swing.JCheckBox();
        jBrandOnlyCheckBox = new javax.swing.JCheckBox();
        jOffTopicCheckBox = new javax.swing.JCheckBox();
        jUntruthfulCheckBox = new javax.swing.JCheckBox();
        jNonSpamCheckBox = new javax.swing.JCheckBox();
        jSpamCheckBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        javax.swing.JButton jTestButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jResultTextArea = new javax.swing.JTextArea();
        jProgressBarAutoTest = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        projectLabel.setFont(new java.awt.Font("Courier New", 1, 28)); // NOI18N
        projectLabel.setText("OPINION SPAM DETECTION");

        jInputTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabelInput.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelInput.setText("Select Input:");

        jLabelOutput.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelOutput.setText("Select Output:");

        jOutputTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jBrowseInputButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jBrowseInputButton.setText("Browse");
        jBrowseInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrowseInputButtonActionPerformed(evt);
            }
        });

        jBrowseOutputButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jBrowseOutputButton.setText("Browse");
        jBrowseOutputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrowseOutputButtonActionPerformed(evt);
            }
        });

        jExitButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jExitButton.setText("Exit");
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Choose type test:");

        jNonReviewCheckBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jNonReviewCheckBox.setText("Non-Review");

        jBrandOnlyCheckBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jBrandOnlyCheckBox.setText("Brand-Only");

        jOffTopicCheckBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jOffTopicCheckBox.setText("Off-Topic");

        jUntruthfulCheckBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jUntruthfulCheckBox.setText("Untruthful");

        jNonSpamCheckBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jNonSpamCheckBox.setText("Non-Spam");

        jSpamCheckBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jSpamCheckBox.setText("Spam");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("By Sub Type: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("By Type:");

        jTestButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTestButton.setText("Test");
        jTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestButtonActionPerformed(evt);
            }
        });

        jResultTextArea.setColumns(20);
        jResultTextArea.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jResultTextArea.setRows(5);
        jScrollPane1.setViewportView(jResultTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jInputTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBrowseInputButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel2)
                                                            .addComponent(jLabel3))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jNonReviewCheckBox)
                                                            .addComponent(jSpamCheckBox))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jNonSpamCheckBox)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jBrandOnlyCheckBox)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jOffTopicCheckBox)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jUntruthfulCheckBox))))
                                                    .addComponent(jLabel1)))
                                            .addComponent(jLabelInput)
                                            .addComponent(jLabelOutput))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE))
                                    .addComponent(jOutputTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBrowseOutputButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jProgressBarAutoTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(projectLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(projectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBrowseInputButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelOutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOutputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBrowseOutputButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNonSpamCheckBox)
                            .addComponent(jSpamCheckBox)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNonReviewCheckBox)
                            .addComponent(jBrandOnlyCheckBox)
                            .addComponent(jOffTopicCheckBox)
                            .addComponent(jUntruthfulCheckBox)
                            .addComponent(jLabel2)))
                    .addComponent(jTestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBarAutoTest, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Process button browse (For user to choose file dataset)
     */
    private void jBrowseInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrowseInputButtonActionPerformed
        new AutoTestHandler().browseInputButtonHandler();
    }//GEN-LAST:event_jBrowseInputButtonActionPerformed

    /**
     * Process button browse (For user to choose directory of file result)
     */
    private void jBrowseOutputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrowseOutputButtonActionPerformed
        new AutoTestHandler().browseOutputButtonHandler();        
    }//GEN-LAST:event_jBrowseOutputButtonActionPerformed

    /**
     * Process button test, auto test begin
     */
    private void jTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestButtonActionPerformed
        OpinionSpamView.autoTestFlag = true;
        new AutoTestHandler().testButtonHandler();
    }//GEN-LAST:event_jTestButtonActionPerformed

    /**
     * Process button exit, after click button exit, program will not terminate
     */
    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_jExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoTestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoTestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoTestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoTestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AutoTestView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JCheckBox jBrandOnlyCheckBox;
    private javax.swing.JButton jBrowseInputButton;
    private javax.swing.JButton jBrowseOutputButton;
    private javax.swing.JButton jExitButton;
    public static javax.swing.JTextField jInputTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelInput;
    private javax.swing.JLabel jLabelOutput;
    public static javax.swing.JCheckBox jNonReviewCheckBox;
    public static javax.swing.JCheckBox jNonSpamCheckBox;
    public static javax.swing.JCheckBox jOffTopicCheckBox;
    public static javax.swing.JTextField jOutputTextField;
    public static javax.swing.JProgressBar jProgressBarAutoTest;
    public static javax.swing.JTextArea jResultTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JCheckBox jSpamCheckBox;
    public static javax.swing.JCheckBox jUntruthfulCheckBox;
    private javax.swing.JLabel projectLabel;
    // End of variables declaration//GEN-END:variables
}
