package view;

import business.processing.PreprocessingModule;
import model.data.Dictionany;
import model.ontology.OntologyProductList;
import model.ontology.OntologyTree;

/**
 *
 * @author LongNguyen & NghiaPham
 */

public class OpinionSpamView extends javax.swing.JFrame {

    /**
     * Creates new form OpinionSpamView
     */
    
    public static boolean testAReviewFlag = false;
    public static boolean autoTestFlag = false;
    
    public OpinionSpamView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectLabel = new javax.swing.JLabel();
        jTestAReviewButton = new javax.swing.JButton();
        jAutoTestButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        projectLabel.setFont(new java.awt.Font("Courier New", 1, 28)); // NOI18N
        projectLabel.setText("OPINION SPAM DETECTION");

        jTestAReviewButton.setFont(new java.awt.Font("Courier New", 0, 19)); // NOI18N
        jTestAReviewButton.setText("Test A Review");
        jTestAReviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestAReviewButtonActionPerformed(evt);
            }
        });

        jAutoTestButton.setFont(new java.awt.Font("Courier New", 0, 19)); // NOI18N
        jAutoTestButton.setText("Auto Test");
        jAutoTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAutoTestButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel1.setText("COPYRIGHT © 2012 BY LONG NGUYEN & NGHIA PHAM");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(projectLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAutoTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTestAReviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(projectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jTestAReviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jAutoTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTestAReviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestAReviewButtonActionPerformed
        // TODO add your handling code here:
        testAReviewFlag = true;
        new TestAReviewView().setVisible(true);
    }//GEN-LAST:event_jTestAReviewButtonActionPerformed

    private void jAutoTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAutoTestButtonActionPerformed
        // TODO add your handling code here:
        autoTestFlag = true;
        new AutoTestView().setVisible(true);
    }//GEN-LAST:event_jAutoTestButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpinionSpamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpinionSpamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpinionSpamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpinionSpamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                /**
                 * Load some static variable before run program:
                 * - initPosTagger(): choose one modal PosTagger and initial PosTagger
                 * - initOntologyData(): Read file ontology and create ontology list
                 * - initUnusualPattern(): create unusual pattern list
                 * - initNonExtremeWord(): extreme words here mean words that show an exaggeration (e.g: better, worse than it really is)
                 * - initSentimentWord(): positive and negative word
                 * - initProductName(): all product name 
                 */                
                PreprocessingModule.initPosTagger();
                PreprocessingModule.initParser();
                OntologyTree.initTree();
                Dictionany.initUnusualPattern();
                Dictionany.initNonExtremeWord(); 
                Dictionany.initSentimentWord();
                OntologyProductList.initProductNameFromOntology();
                                  
                /**
                 * Run program
                 */
                new OpinionSpamView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAutoTestButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jTestAReviewButton;
    private javax.swing.JLabel projectLabel;
    // End of variables declaration//GEN-END:variables
}
