package view;

import controller.TestAReviewHandler;

/**
 *
 * @author LongNguyen & NghiaPham
 */

public class TestAReviewView extends javax.swing.JFrame {

    /**
     * Creates new form TestAReviewView
     */
        
    public TestAReviewView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jResultTextField = new javax.swing.JTextField();
        jCheckButton = new javax.swing.JButton();
        projectLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        commentLabel = new javax.swing.JLabel();
        jproductTypeLabel = new javax.swing.JLabel();
        jExitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jReviewTextArea = new javax.swing.JTextArea();
        jProgressBarTestAReview = new javax.swing.JProgressBar();
        jTime = new javax.swing.JLabel();
        jProductTypeComboBox = new javax.swing.JComboBox();
        jProductNameLabel = new javax.swing.JLabel();
        jProductNameComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jResultTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jCheckButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jCheckButton.setText("Check");
        jCheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckButtonActionPerformed(evt);
            }
        });

        projectLabel.setFont(new java.awt.Font("Courier New", 1, 28)); // NOI18N
        projectLabel.setText("OPINION SPAM DETECTION");

        resultLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        resultLabel.setText("Result:");

        commentLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        commentLabel.setText("Your review:");

        jproductTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jproductTypeLabel.setText("Product Type:");

        jExitButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jExitButton.setText("Exit");
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jReviewTextArea.setColumns(20);
        jReviewTextArea.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jReviewTextArea.setLineWrap(true);
        jReviewTextArea.setRows(5);
        jScrollPane1.setViewportView(jReviewTextArea);

        jTime.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jProductTypeComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jProductTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please Select Product Type ...", "Mobile Phone", "Laptop & Tablet", "Camera", "Hotel" }));
        jProductTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductTypeComboBoxActionPerformed(evt);
            }
        });

        jProductNameLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jProductNameLabel.setText("Product Name: ");

        jProductNameComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jResultTextField)
                            .addComponent(jProgressBarTestAReview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTime, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resultLabel)
                                    .addComponent(jproductTypeLabel)
                                    .addComponent(commentLabel)
                                    .addComponent(jProductTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jProductNameComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jProductNameLabel)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 182, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(projectLabel)
                                .addGap(186, 186, 186))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCheckButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(332, 332, 332))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(projectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jproductTypeLabel)
                    .addComponent(jProductNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProductTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProductNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(resultLabel)
                .addGap(4, 4, 4)
                .addComponent(jResultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarTestAReview, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTime.getAccessibleContext().setAccessibleName("jTime");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Process button check. After user click button check, the program will check a review
     */
    private void jCheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckButtonActionPerformed
        OpinionSpamView.testAReviewFlag = true;
        new TestAReviewHandler().checkButtonHandler();
    }//GEN-LAST:event_jCheckButtonActionPerformed

    /**
     * Process button exit, after user click button exit, program will not terminate
     */
    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_jExitButtonActionPerformed

    /**
     * Process product type combo box
     */
    private void jProductTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductTypeComboBoxActionPerformed
        new TestAReviewHandler().productTypeComboBoxHandler();
    }//GEN-LAST:event_jProductTypeComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestAReviewView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestAReviewView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestAReviewView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestAReviewView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TestAReviewView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel commentLabel;
    private javax.swing.JButton jCheckButton;
    private javax.swing.JButton jExitButton;
    public static javax.swing.JComboBox jProductNameComboBox;
    private javax.swing.JLabel jProductNameLabel;
    public static javax.swing.JComboBox jProductTypeComboBox;
    public static javax.swing.JProgressBar jProgressBarTestAReview;
    public static javax.swing.JTextField jResultTextField;
    public static javax.swing.JTextArea jReviewTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel jTime;
    private javax.swing.JLabel jproductTypeLabel;
    private javax.swing.JLabel projectLabel;
    private javax.swing.JLabel resultLabel;
    // End of variables declaration//GEN-END:variables
}
